export const trackCategories: Record<string, string> = {
  'AmonComplex': 'TFE',
  'AmonComplex2': 'TFE',
  'DesertTemple': 'TFE',
  'Dunes': 'TFE',
  'GreatPyramid': 'TFE',
  'Hatshepsut': 'TFE',
  'KarnakApproaching': 'TFE',
  'KarnakEnterComplex': 'TFE',
  'Oasis': 'TFE',
  'RedCanyon': 'TFE',
  'RichYards': 'TFE',
  'ThebesMetropolis': 'TFE',
  'ThebesSewers': 'TFE',
  'ThebesSuburbs': 'TFE',
  'TombOfRamses': 'TFE',
  'YellowTerrain': 'TFE',
  'DreamWaterfalls': 'TFE',

  'CorridorOfDeath': 'TSE',
  'Courtyards': 'TSE',
  'GothicCastle': 'TSE',
  'LandOfDamned': 'TSE',
  'Palenque1': 'TSE',
  'Palenque2': 'TSE',
  'Persepolis': 'TSE',
  'SerpentYards': 'TSE',
  'Teotihuacan1': 'TSE',
  'ThePit': 'TSE',
  'TowerOfBabylon': 'TSE',
  'Ziggurrat': 'TSE',

  'BetaYellowTerrain': 'v0.10',
  'BetaOasis': 'v0.10',
  'BetaDreamWaterfalls': 'v0.10',

  'CutScenes': 'Misc',
  'Fight': 'Fight',
  'Multiplayer': 'Misc',
};

export const tabs: string[] = [
  'All',
  'TFE',
  'TSE',
  'v0.10',
  'Fight',
  'Misc',
];